Repository michael-mosler/Pius-App-for-Android, pull requests merged in 2021-04, with the labels that each got.

#32 Adding autofill hints
  app/src/main/res/layout/fragment_preferences_general.xml
Labels: enhancement

#40 Fixed issue #36.
  .idea/modules.xml
  app/src/main/java/com/rmkrings/data/adapter/VertretungsplanListAdapter.java
  build.gradle
Labels: bug

#45 23 Open source notice
  app/src/main/res/values/strings.xml
Labels: documentation

#41 GitHub changelog file: v1.7.0
  CHANGELOG.md
Labels: documentation
